language: java
sudo: false
install: true

addons:
  sonarcloud:
    organization: "sonar-intellij-plugin"
    token:
      secure: "f98e0adaa69bd0ead0cffe21ff6edbc51501125f"

jdk:
  - openjdk8

script:
  - ./gradlew sonarqube

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle'
    - '.gradle'
